version: '3.8'

services:
  luxe-network-inventory:
    build: .
    container_name: luxe_network_inventory
    ports:
      - "8787:8787"
    volumes:
      - network_db_data:/app/instance
    restart: unless-stopped

volumes:
  network_db_data:
